# Generated by Django 3.2.5 on 2021-07-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('goalCalories', models.CharField(max_length=20)),
                ('goalCaloriesRatio', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('goalStepCount', models.CharField(max_length=20)),
            ],
        ),
    ]
