# Generated by Django 3.2.5 on 2021-07-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
