# Generated by Django 3.2.5 on 2021-07-09 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcapp', '0002_account_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.CharField(max_length=20)),
                ('foodName', models.CharField(max_length=100)),
                ('carb', models.CharField(max_length=20)),
                ('prot', models.CharField(max_length=20)),
                ('fat', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='dmgcapp.account')),
            ],
        ),
    ]
