# Generated by Django 3.2.5 on 2021-07-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcapp', '0003_todaycalories'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaycalories',
            name='foodCode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
